// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"challenge-app/internal/application/service"
	"challenge-app/internal/application/service/interface"
	"challenge-app/internal/domain/repository"
	"challenge-app/internal/infrastructure/repository/postgres"
	"challenge-app/internal/presentation/handler"
	handler2 "challenge-app/internal/presentation/handler/interface"
	"challenge-app/internal/presentation/middleware"
	middleware2 "challenge-app/internal/presentation/middleware/interface"
	"challenge-app/internal/presentation/router"
	"challenge-app/pkg/security"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// InitializeRouter wires up all dependencies and returns the Gin engine.
func InitializeRouter(db *gorm.DB, jwtSecret string, tokenExpiry time.Duration) (*gin.Engine, error) {
	userRepository := postgres.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	passwordServiceImpl := security.NewPasswordService()
	jwtServiceImpl := security.NewJWTService(jwtSecret, tokenExpiry)
	authService := service.NewAuthService(userRepository, passwordServiceImpl, jwtServiceImpl)
	authHandler := handler.NewAuthHandler(authService)
	jwtMiddleware := middleware.NewJWTMiddleware(jwtServiceImpl)
	engine := router.SetupRouter(userHandler, authHandler, jwtMiddleware)
	return engine, nil
}

// wire.go:

// Security & JWT
var SecurityProvideSet = wire.NewSet(security.NewPasswordService, security.NewJWTService, wire.Bind(new(security.PasswordService), new(*security.PasswordServiceImpl)), wire.Bind(new(security.JWTService), new(*security.JwtServiceImpl)))

// Repositories
var RepoProvideSet = wire.NewSet(postgres.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*postgres.UserRepository)))

// Services
var ServiceProvideSet = wire.NewSet(service.NewUserService, service.NewAuthService, wire.Bind(new(serviceinterface.AuthServicer), new(*service.AuthService)), wire.Bind(new(serviceinterface.UserServicer), new(*service.UserService)))

// Handlers
var HandlerProvideSet = wire.NewSet(handler.NewUserHandler, handler.NewAuthHandler, wire.Bind(new(handler2.UserHandler), new(*handler.UserHandler)), wire.Bind(new(handler2.AuthHandler), new(*handler.AuthHandler)))

// Middleware
var MiddlewareProvideSet = wire.NewSet(middleware.NewJWTMiddleware, wire.Bind(new(middleware2.JWTMiddleware), new(*middleware.JWTMiddleware)))
