// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"challenge-app/internal/application/service"
	"challenge-app/internal/application/service/interface"
	"challenge-app/internal/bootstrap"
	"challenge-app/internal/domain/repository"
	"challenge-app/internal/infrastructure/repository/postgres"
	"challenge-app/internal/infrastructure/repository/postgres/driver"
	"challenge-app/internal/infrastructure/repository/redis"
	"challenge-app/internal/presentation/handler"
	handler2 "challenge-app/internal/presentation/handler/interface"
	"challenge-app/internal/presentation/middleware"
	middleware2 "challenge-app/internal/presentation/middleware/interface"
	"challenge-app/internal/presentation/router"
	"challenge-app/pkg/email"
	"challenge-app/pkg/security"
	"challenge-app/pkg/validation"
	"context"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	redis2 "github.com/go-redis/redis/v8"
	"github.com/google/wire"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// --- Initialize Router ---
func InitializeRouter(db *gorm.DB, validator2 *validator.Validate) (*gin.Engine, error) {
	userRepository := postgres.NewUserRepository(db)
	client, err := ProvideRedisClient()
	if err != nil {
		return nil, err
	}
	verificationRepository := redis.NewVerificationRepository(client)
	env := bootstrap.LoadEnv()
	emailServiceImpl := ProvideEmailService(env)
	userService := service.NewUserService(userRepository, verificationRepository, emailServiceImpl)
	userHandler := handler.NewUserHandler(userService)
	jwtServiceImpl := ProvideJWTService(env)
	passwordServiceImpl := security.NewPasswordService()
	authService := service.NewAuthService(userRepository, verificationRepository, jwtServiceImpl, emailServiceImpl, passwordServiceImpl)
	authHandler := handler.NewAuthHandler(authService)
	followRepository := postgres.NewFollowRepository(db)
	followService := service.NewFollowService(followRepository, userRepository)
	followHandlerImpl := handler.NewFollowHandler(followService)
	challengeRepository := postgres.NewChallengeRepository(db)
	challengeParticipantRepository := postgres.NewChallengeParticipantRepository(db)
	challengeCommentRepository := postgres.NewChallengeCommentRepository(db)
	challengeInviteRepository := postgres.NewChallengeInviteRepository(db)
	challengeRequestRepository := postgres.NewChallengeRequestRepository(db)
	categoryRepository := postgres.NewCategoryRepository(db)
	challengeService := service.NewChallengeService(challengeRepository, challengeParticipantRepository, challengeCommentRepository, challengeInviteRepository, challengeRequestRepository, categoryRepository, userRepository)
	challengeHandler := handler.NewChallengeHandler(challengeService)
	jwtMiddleware := middleware.NewJWTMiddleware(jwtServiceImpl)
	errorMiddleware := middleware.NewErrorProvider()
	engine := router.SetupRouter(userHandler, authHandler, followHandlerImpl, challengeHandler, jwtMiddleware, errorMiddleware)
	return engine, nil
}

// --- Initialize Full Application ---
func InitializeApplication() (*Application, error) {
	postgresDSN := ProvideDSN()
	db, err := ProvidePostgresDB(postgresDSN)
	if err != nil {
		return nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	client, err := ProvideRedisClient()
	if err != nil {
		return nil, err
	}
	verificationRepository := redis.NewVerificationRepository(client)
	env := bootstrap.LoadEnv()
	emailServiceImpl := ProvideEmailService(env)
	userService := service.NewUserService(userRepository, verificationRepository, emailServiceImpl)
	userHandler := handler.NewUserHandler(userService)
	jwtServiceImpl := ProvideJWTService(env)
	passwordServiceImpl := security.NewPasswordService()
	authService := service.NewAuthService(userRepository, verificationRepository, jwtServiceImpl, emailServiceImpl, passwordServiceImpl)
	authHandler := handler.NewAuthHandler(authService)
	followRepository := postgres.NewFollowRepository(db)
	followService := service.NewFollowService(followRepository, userRepository)
	followHandlerImpl := handler.NewFollowHandler(followService)
	challengeRepository := postgres.NewChallengeRepository(db)
	challengeParticipantRepository := postgres.NewChallengeParticipantRepository(db)
	challengeCommentRepository := postgres.NewChallengeCommentRepository(db)
	challengeInviteRepository := postgres.NewChallengeInviteRepository(db)
	challengeRequestRepository := postgres.NewChallengeRequestRepository(db)
	categoryRepository := postgres.NewCategoryRepository(db)
	challengeService := service.NewChallengeService(challengeRepository, challengeParticipantRepository, challengeCommentRepository, challengeInviteRepository, challengeRequestRepository, categoryRepository, userRepository)
	challengeHandler := handler.NewChallengeHandler(challengeService)
	jwtMiddleware := middleware.NewJWTMiddleware(jwtServiceImpl)
	errorMiddleware := middleware.NewErrorProvider()
	engine := router.SetupRouter(userHandler, authHandler, followHandlerImpl, challengeHandler, jwtMiddleware, errorMiddleware)
	application := NewApplication(db, engine)
	return application, nil
}

// wire.go:

type PostgresDSN string

type JWTSecret string

type TokenExpiry time.Duration

type RedisClient *redis2.Client

// --- Providers ---
func ProvideDSN() PostgresDSN {
	cfg := bootstrap.LoadEnv()
	dsn := "host=" + cfg.Database.Host +
		" user=" + cfg.Database.User +
		" password=" + cfg.Database.Password +
		" dbname=" + cfg.Database.Name +
		" port=" + cfg.Database.Port +
		" sslmode=" + cfg.Database.SSLMode
	return PostgresDSN(dsn)
}

func ProvidePostgresDB(dsn PostgresDSN) (*gorm.DB, error) {
	return driver.InitPostgresDB(string(dsn))
}

func ProvideRedisClient() (*redis2.Client, error) {
	cfg := bootstrap.LoadEnv()

	client := redis2.NewClient(&redis2.Options{
		Addr:     cfg.Redis.Address + ":" + cfg.Redis.Port,
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
	})

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if _, err := client.Ping(ctx).Result(); err != nil {
		return nil, err
	}
	return client, nil
}

func ProvideEmailService(cfg *bootstrap.Env) *email.EmailServiceImpl {
	return email.NewEmailService(cfg)
}

func ProvideJWTService(cfg *bootstrap.Env) *security.JwtServiceImpl {
	return security.NewJWTService(cfg)
}

func ProvideValidator() *validator.Validate {
	v := validator.New()
	v.RegisterValidation("password_policy", validation.PasswordValidationFunc)
	return v
}

// --- Provider Sets ---
var SecurityProviderSet = wire.NewSet(security.NewPasswordService, ProvideJWTService, wire.Bind(new(security.PasswordService), new(*security.PasswordServiceImpl)), wire.Bind(new(security.JWTService), new(*security.JwtServiceImpl)))

var DatabaseProviderSet = wire.NewSet(
	ProvideDSN,
	ProvidePostgresDB,
)

var RedisProviderSet = wire.NewSet(
	ProvideRedisClient, redis.NewVerificationRepository, wire.Bind(new(repository.VerificationRepository), new(*redis.VerificationRepository)),
)

var EmailProviderSet = wire.NewSet(bootstrap.LoadEnv, ProvideEmailService, wire.Bind(new(email.EmailService), new(*email.EmailServiceImpl)))

var RepositoryProviderSet = wire.NewSet(postgres.NewUserRepository, postgres.NewChallengeRepository, postgres.NewCategoryRepository, postgres.NewChallengeInviteRepository, postgres.NewChallengeParticipantRepository, postgres.NewChallengeCommentRepository, postgres.NewChallengeRequestRepository, wire.Bind(new(repository.ChallengeRequestRepository), new(*postgres.ChallengeRequestRepository)), wire.Bind(new(repository.ChallengeCommentRepository), new(*postgres.ChallengeCommentRepository)), wire.Bind(new(repository.ChallengeInviteRepository), new(*postgres.ChallengeInviteRepository)), wire.Bind(new(repository.ChallengeParticipantRepository), new(*postgres.ChallengeParticipantRepository)), wire.Bind(new(repository.UserRepository), new(*postgres.UserRepository)), wire.Bind(new(repository.ChallengeRepository), new(*postgres.ChallengeRepository)), wire.Bind(new(repository.CategoryRepository), new(*postgres.CategoryRepository)))

var ServiceProviderSet = wire.NewSet(service.NewUserService, service.NewAuthService, service.NewChallengeService, wire.Bind(new(serviceinterface.ChallengeServicer), new(*service.ChallengeService)), wire.Bind(new(serviceinterface.UserServicer), new(*service.UserService)), wire.Bind(new(serviceinterface.AuthServicer), new(*service.AuthService)))

var HandlerProviderSet = wire.NewSet(handler.NewUserHandler, handler.NewAuthHandler, handler.NewChallengeHandler, wire.Bind(new(handler2.UserHandler), new(*handler.UserHandler)), wire.Bind(new(handler2.AuthHandler), new(*handler.AuthHandler)), wire.Bind(new(handler2.ChallengeHandler), new(*handler.ChallengeHandler)))

var MiddlewareProviderSet = wire.NewSet(middleware.NewJWTMiddleware, middleware.NewErrorProvider, wire.Bind(new(middleware2.ErrorMiddleware), new(*middleware.ErrorMiddleware)), wire.Bind(new(middleware2.JWTMiddleware), new(*middleware.JWTMiddleware)))

var FollowProviderSet = wire.NewSet(postgres.NewFollowRepository, service.NewFollowService, handler.NewFollowHandler, wire.Bind(new(repository.FollowRepository), new(*postgres.FollowRepository)), wire.Bind(new(serviceinterface.FollowServicer), new(*service.FollowService)), wire.Bind(new(handler2.FollowHandler), new(*handler.FollowHandlerImpl)))

// --- Application ---
type Application struct {
	DB     *gorm.DB
	Router *gin.Engine
}

func NewApplication(db *gorm.DB, router2 *gin.Engine) *Application {
	return &Application{
		DB:     db,
		Router: router2,
	}
}
