// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"challenge-app/internal/application/service"
	"challenge-app/internal/application/service/interface"
	"challenge-app/internal/bootstrap"
	"challenge-app/internal/domain/repository"
	"challenge-app/internal/infrastructure/repository/postgres"
	"challenge-app/internal/infrastructure/repository/postgres/driver"
	"challenge-app/internal/presentation/handler"
	handler2 "challenge-app/internal/presentation/handler/interface"
	"challenge-app/internal/presentation/middleware"
	middleware2 "challenge-app/internal/presentation/middleware/interface"
	"challenge-app/internal/presentation/router"
	"challenge-app/pkg/security"
	"challenge-app/pkg/validation"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// --- Initialize Router ---
func InitializeRouter(db *gorm.DB, validator2 *validator.Validate) (*gin.Engine, error) {
	userRepository := postgres.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	passwordServiceImpl := security.NewPasswordService()
	jwtConfig := ProvideJWTConfig()
	jwtServiceImpl := ProvideJWTService(jwtConfig)
	authService := service.NewAuthService(userRepository, passwordServiceImpl, jwtServiceImpl)
	authHandler := handler.NewAuthHandler(authService)
	jwtMiddleware := middleware.NewJWTMiddleware(jwtServiceImpl)
	engine := router.SetupRouter(userHandler, authHandler, jwtMiddleware)
	return engine, nil
}

// --- Initialize Full Application ---
func InitializeApplication() (*Application, error) {
	postgresDSN := ProvideDSN()
	db, err := ProvidePostgresDB(postgresDSN)
	if err != nil {
		return nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	passwordServiceImpl := security.NewPasswordService()
	jwtConfig := ProvideJWTConfig()
	jwtServiceImpl := ProvideJWTService(jwtConfig)
	authService := service.NewAuthService(userRepository, passwordServiceImpl, jwtServiceImpl)
	authHandler := handler.NewAuthHandler(authService)
	jwtMiddleware := middleware.NewJWTMiddleware(jwtServiceImpl)
	engine := router.SetupRouter(userHandler, authHandler, jwtMiddleware)
	application := NewApplication(db, engine)
	return application, nil
}

// wire.go:

type PostgresDSN string

type JWTSecret string

type TokenExpiry time.Duration

// --- Providers ---
func ProvideDSN() PostgresDSN {
	cfg := bootstrap.LoadEnv()
	dsn := "host=" + cfg.DBHost +
		" user=" + cfg.DBUser +
		" password=" + cfg.DBPassword +
		" dbname=" + cfg.DBName +
		" port=" + cfg.DBPort +
		" sslmode=" + cfg.SSLMode
	return PostgresDSN(dsn)
}

func ProvideJWTSecret() JWTSecret {
	cfg := bootstrap.LoadEnv()
	return JWTSecret(cfg.JWTSecretKey)
}

func ProvideTokenExpiry() TokenExpiry {
	return TokenExpiry(bootstrap.JWTTokenExpiry)
}

func ProvidePostgresDB(dsn PostgresDSN) (*gorm.DB, error) {
	return driver.InitPostgresDB(string(dsn))
}

type JWTConfig struct {
	Secret string
	Expiry time.Duration
	Issuer string
}

func ProvideJWTConfig() JWTConfig {

	return JWTConfig{
		Secret: string(ProvideJWTSecret()),
		Expiry: time.Duration(ProvideTokenExpiry()),
		Issuer: bootstrap.JWTIssuer,
	}
}

func ProvideJWTService(cfg JWTConfig) *security.JwtServiceImpl {
	return security.NewJWTService(cfg.Secret, cfg.Expiry, cfg.Issuer)
}

func ProvideValidator() *validator.Validate {
	v := validator.New()
	v.RegisterValidation("password_policy", validation.PasswordValidationFunc)
	return v
}

// --- Provider Sets ---
var SecurityProviderSet = wire.NewSet(security.NewPasswordService, ProvideJWTService,
	ProvideJWTConfig, wire.Bind(new(security.PasswordService), new(*security.PasswordServiceImpl)), wire.Bind(new(security.JWTService), new(*security.JwtServiceImpl)),
)

var DatabaseProviderSet = wire.NewSet(
	ProvideDSN,
	ProvidePostgresDB,
)

var RepositoryProviderSet = wire.NewSet(postgres.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*postgres.UserRepository)))

var ServiceProviderSet = wire.NewSet(service.NewUserService, service.NewAuthService, wire.Bind(new(serviceinterface.UserServicer), new(*service.UserService)), wire.Bind(new(serviceinterface.AuthServicer), new(*service.AuthService)))

var HandlerProviderSet = wire.NewSet(handler.NewUserHandler, handler.NewAuthHandler, wire.Bind(new(handler2.UserHandler), new(*handler.UserHandler)), wire.Bind(new(handler2.AuthHandler), new(*handler.AuthHandler)))

var MiddlewareProviderSet = wire.NewSet(middleware.NewJWTMiddleware, middleware.NewErrorProvider, wire.Bind(new(middleware2.ErrorMiddleware), new(*middleware.ErrorMiddleware)), wire.Bind(new(middleware2.JWTMiddleware), new(*middleware.JWTMiddleware)))

// --- Application ---
type Application struct {
	DB     *gorm.DB
	Router *gin.Engine
}

func NewApplication(db *gorm.DB, router2 *gin.Engine) *Application {
	return &Application{
		DB:     db,
		Router: router2,
	}
}
