package localization

var English = map[string]interface{}{
	"title":            "Title",
	"description":      "Description",
	"categoryID":       "Category",
	"category_id":      "Category",
	"maxParticipants":  "Max Participants",
	"max_participants": "Max Participants",
	"visibility":       "Visibility",
	"location":         "Location",
	"latitude":         "Latitude",
	"longitude":        "Longitude",
	"address":          "Address",
	"goal":             "Goal",
	"rule":             "Rule",
	"startTime":        "Start Time",
	"start_time":       "Start Time",
	"endTime":          "End Time",
	"end_time":         "End Time",
	"timezone":         "Timezone",
	"file":             "File",

	"id":           "ID",
	"user_id":      "User ID",
	"challenge_id": "Challenge ID",
	"post_id":      "Post ID",
	"comment_id":   "Comment ID",
	"invite_id":    "Invite ID",
	"request_id":   "Request ID",

	"date":      "Date",
	"start":     "Start Date",
	"end":       "End Date",
	"query":     "Search Query",
	"content":   "Content",
	"parent_id": "Parent ID",

	"email":     "Email",
	"newEmail":  "New Email",
	"new_email": "New Email",
	"oldEmail":  "Old Email",
	"old_email": "Old Email",
	"code":      "Code",

	"username": "Username",
	"bio":      "Bio",

	"progress": "Progress",
	"feeling":  "Feeling",
	"note":     "Note",

	"count":        "Count",
	"contentType":  "Content Type",
	"content_type": "Content Type",

	"fields": map[string]interface{}{
		"title":            "Title",
		"description":      "Description",
		"categoryID":       "Category",
		"category_id":      "Category",
		"maxParticipants":  "Max Participants",
		"max_participants": "Max Participants",
		"visibility":       "Visibility",
		"location":         "Location",
		"latitude":         "Latitude",
		"longitude":        "Longitude",
		"address":          "Address",
		"goal":             "Goal",
		"rule":             "Rule",
		"startTime":        "Start Time",
		"start_time":       "Start Time",
		"endTime":          "End Time",
		"end_time":         "End Time",
		"timezone":         "Timezone",
		"file":             "File",

		"id":           "ID",
		"user_id":      "User ID",
		"challenge_id": "Challenge ID",
		"post_id":      "Post ID",
		"comment_id":   "Comment ID",
		"invite_id":    "Invite ID",
		"request_id":   "Request ID",

		"date":      "Date",
		"start":     "Start Date",
		"end":       "End Date",
		"query":     "Search Query",
		"content":   "Content",
		"parent_id": "Parent ID",

		"email":     "Email",
		"newEmail":  "New Email",
		"new_email": "New Email",
		"oldEmail":  "Old Email",
		"old_email": "Old Email",
		"code":      "Code",

		"username": "Username",
		"bio":      "Bio",

		"progress": "Progress",
		"feeling":  "Feeling",
		"note":     "Note",

		"count":        "Count",
		"contentType":  "Content Type",
		"content_type": "Content Type",
	},

	"errors": map[string]interface{}{
		// Generic
		"generic":  "An error occurred. Please try again.",
		"internal": "Internal server error.",

		// Auth / JWT
		"AUTH_MISSING_ID":          "You must be logged in first.",
		"AUTH_HEADER_MALFORMED":    "Invalid auth header. Expected format: Bearer <token>",
		"TOKEN_EMPTY":              "Token is missing.",
		"TOKEN_INVALID_EXPIRED":    "Token is invalid or expired.",
		"AUTH_INVALID_CREDENTIALS": "Invalid username or password.",

		// Conflict (User, etc.)
		"USER_ALREADY_EXISTS":          "A user with these details already exists.",
		"USER_ALREADY_EXISTS_EMAIL":    "A user with this email already exists.",
		"USER_ALREADY_EXISTS_USERNAME": "This username is already taken.",
		"USER_UPDATE_CONFLICT":         "Username or email already exists.",
		"USER_NOT_FOUND":               "User not found.",
		"EMAIL_TAKEN":                  "This email is already registered.",

		// Validation
		"INPUT_VALIDATION_FAILED": "Input validation failed.",
		"INVALID_REQUEST_BODY":    "Invalid request body.",
		"INVALID_URI_PARAMS":      "Invalid URI parameters.",
		"INVALID_PARAM":           "Invalid value for {0}.",
		"INVALID_TIME_FORMAT":     "Invalid time format for {0}.",
		"INVALID_DATE_FORMAT":     "Invalid date format for {0}.",
		"USERNAME_REQUIRED":       "Username is required.",
		"EMAIL_REQUIRED":          "Email is required.",
		"PASSWORD_REQUIRED":       "Password is required.",
		"EMAIL_SAME":              "New email cannot be the same as current email.",

		// Validator tags (from go-playground/validator)
		"required": "The {0} field is required.",
		"min":      "{0} must be at least {1}.",
		"max":      "{0} must be at most {1}.",
		"len":      "The length of {0} must be exactly {1}.",
		"email":    "Invalid email format.",
		"oneof":    "Invalid value for {0}.",
		"datetime": "Invalid date/time format for {0}.",
		"numeric":  "{0} must be numeric.",
		"alphanum": "{0} must be alphanumeric.",
		"ascii":    "{0} must contain only ASCII characters.",
		"gte":      "{0} must be greater than or equal to {1}.",
		"lte":      "{0} must be less than or equal to {1}.",
		"gt":       "{0} must be greater than {1}.",
		"lt":       "{0} must be less than {1}.",
		"eqfield":  "{0} must match {1}.",
		"nefield":  "{0} must not match {1}.",
		"uuid":     "{0} must be a valid UUID.",
		"url":      "{0} must be a valid URL.",
		"base64":   "{0} must be a valid base64 string.",

		// Verification
		"VERIFY_CODE_INVALID":   "Invalid verification code.",
		"VERIFY_CODE_EXPIRED":   "Verification code has expired.",
		"EMAIL_CHANGE_EXPIRED":  "Email change request has expired.",
		"EMAIL_CHANGE_MISMATCH": "Email change request does not match the user.",

		// Uploads & Media
		"INVALID_PROFILE_PICTURE": "Invalid profile picture.",
		"INVALID_CONTENT_TYPE":    "Content type not supported.",
		"S3_UPLOAD_FAILED":        "Image upload failed.",
		"COVER_FORBIDDEN":         "Only the creator can change the cover image.",
		"POST_TOO_MANY_IMAGES":    "Maximum 10 images allowed.",
		"INVALID_TEMP_KEY":        "Invalid temporary key.",
		"TEMP_VERIFY_FAILED":      "Temporary key verification failed.",
		"TEMP_KEY_NOT_OWNED":      "Temporary key is expired or does not belong to you.",
		"COMMIT_FAILED":           "Image commit failed.",
		"PRESIGN_FAILED":          "Failed to generate upload URL.",

		// Posts
		"POST_CREATE_BAD_INPUT": "Invalid input.",
		"POST_NOT_FOUND":        "Post not found.",
		"POST_UPDATE_FORBIDDEN": "Only the post creator can edit it.",
		"POST_DELETE_FORBIDDEN": "Only the post creator can delete it.",
		"LIKE_BAD_INPUT":        "Invalid input.",
		"UNLIKE_BAD_INPUT":      "Invalid input.",
		"USER_NOT_LIKED":        "You have not liked this item.",
		"USER_ALREADY_LIKED":    "You have already liked this item.",
		"INVALID_ENTITY_TYPE":   "Invalid entity type.",
		"COMMENT_ADD_BAD_INPUT": "Invalid input.",
		"COMMENT_NOT_FOUND":     "Comment not found.",

		// Challenges
		"CHALLENGE_CREATE_BAD_INPUT":          "Invalid input.",
		"CHALLENGE_NOT_FOUND":                 "Challenge not found.",
		"CHALLENGE_UPDATE_FORBIDDEN":          "Only the creator can edit the challenge.",
		"CHALLENGE_DELETE_FORBIDDEN":          "Only the creator can delete the challenge.",
		"STOP_CHALLENGE_NOT_AUTHORIZED":       "Only the creator can stop the challenge.",
		"INVALID_MAP_COORDINATES":             "Invalid map coordinates.",
		"MISSING_MAP_COORDINATES":             "Latitude and longitude are required.",
		"INVALID_GOAL":                        "Goal must be at least 1.",
		"CHALLENGE_PARTICIPANT_LIMIT_REACHED": "Maximum participant limit reached.",
		"CHALLENGE_NOT_PUBLIC":                "Challenge is not public.",
		"CHALLENGE_NOT_PRIVATE":               "Challenge is not private.",
		"CHALLENGE_STOPPED":                   "Challenge has been stopped.",
		"USER_ALREADY_PARTICIPANT":            "You are already a participant in this challenge.",
		"USER_NOT_PARTICIPANT":                "User is not a participant in this challenge.",
		"PARTICIPANTS_ACCESS_DENIED":          "Access to participants is not allowed.",
		"INVITES_ACCESS_DENIED":               "Only the creator can view invites.",
		"REMOVE_PARTICIPANT_NOT_AUTHORIZED":   "Only the creator can remove participants.",
		"JOIN_REQUEST_ALREADY_EXISTS":         "Join request already exists.",
		"JOIN_REQUEST_NOT_FOUND":              "Join request not found.",
		"JOIN_REQUEST_NOT_PENDING":            "Join request is not pending.",
		"JOIN_REQUEST_NOT_AUTHORIZED":         "You are not authorized to perform this action.",
		"INVITE_NOT_FOUND":                    "Invite not found.",
		"INVITE_NOT_PENDING":                  "Invite is not pending.",
		"INVITE_NOT_AUTHORIZED":               "You are not authorized to send this invite.",
		"COMMENTS_DISABLED":                   "Comments are disabled for this challenge.",

		// IDs
		"INVALID_USER_ID":      "Invalid user ID.",
		"INVALID_POST_ID":      "Invalid post ID.",
		"INVALID_CHALLENGE_ID": "Invalid challenge ID.",
		"INVALID_COMMENT_ID":   "Invalid comment ID.",
		"INVALID_INVITE_ID":    "Invalid invite ID.",
		"INVALID_REQUEST_ID":   "Invalid request ID.",

		// UserDay
		"USER_ID_REQUIRED":      "User ID is required.",
		"CHALLENGE_ID_REQUIRED": "Challenge ID is required.",
		"NOTE_EMPTY":            "Note cannot be empty.",
		"INVALID_FEELING":       "Feeling must be 'good' or 'bad'.",
		"INVALID_DATE_RANGE":    "Start date must be before end date.",
		"INVALID_GOAL_VALUE":    "Progress value must be between 0 and 100.",

		// Follow
		"SELF_FOLLOW_FORBIDDEN": "You cannot follow yourself.",
		"FOLLOW_ALREADY_EXISTS": "You are already following this user.",
		"FOLLOW_NOT_FOUND":      "Follow relationship not found.",
		"FOLLOWER_NOT_FOUND":    "Requested follower not found.",

		// System / Internal
		"DB_OPERATION_FAILED":      "Database operation failed.",
		"SYSTEM_HASH_FAIL":         "Internal server error.",
		"SYSTEM_JWT_FAIL":          "Internal server error.",
		"SYSTEM_VERIFY_FAIL":       "Internal server error.",
		"SYSTEM_EMAIL_FAIL":        "Internal server error.",
		"DB_LOGIN_FAIL":            "Internal server error.",
		"DB_VERIFY_FAIL":           "Internal server error.",
		"DB_UPDATE_FAIL":           "Internal server error.",
		"VERIFY_CODE_GEN_FAIL":     "Internal server error.",
		"CONTEXT_CAST_FAIL":        "Internal server error.",
		"CODE_LOGIC_ERROR":         "Internal server error.",
		"CODE_DATA_CORRUPT":        "Internal server error.",
		"STORAGE_OPERATION_FAILED": "Storage operation failed.",
	},

	"success": map[string]interface{}{
		"PROFILE_UPDATED":                "Profile updated successfully.",
		"PROFILE_EMAIL_UPDATED_RELOGIN":  "Profile and email updated. Please log in again.",
		"EMAIL_CHANGE_VERIFICATION_SENT": "Verification email sent to your new email address.",
		"EMAIL_CHANGED_SUCCESSFULLY":     "Email changed successfully.",
		"USER_DELETED_SUCCESSFULLY":      "User deleted successfully.",
		"PROFILE_PICTURE_UPLOADED":       "Profile picture uploaded successfully.",
		"CHALLENGE_CREATED":              "Challenge created successfully.",
		"CHALLENGE_UPDATED":              "Challenge updated successfully.",
		"CHALLENGE_DELETED":              "Challenge deleted successfully.",
		"DAY_DATA_SAVED":                 "Day data saved.",
		"DAY_DATA_UPDATED":               "Day data updated.",
		"DAY_DATA_DELETED":               "Day data deleted.",
		"FOLLOW_SUCCESS":                 "User followed successfully.",
		"UNFOLLOW_SUCCESS":               "Follow removed successfully.",
		"CHALLENGE_JOINED":               "Successfully joined the challenge.",
		"CHALLENGE_LEFT":                 "Left the challenge.",
		"INVITE_SENT":                    "Invite sent successfully.",
		"INVITE_ACCEPTED":                "Invite accepted.",
		"INVITE_DECLINED":                "Invite declined.",
		"REQUEST_SENT":                   "Join request sent.",
		"REQUEST_ACCEPTED":               "Join request accepted.",
		"REQUEST_DECLINED":               "Join request declined.",
		"COMMENT_ADDED":                  "Comment posted successfully.",
		"LIKE_ADDED":                     "Post liked.",
		"LIKE_REMOVED":                   "Like removed.",
		"USER_REGISTERED":                "User registered successfully. Please check your email for verification.",
	},

	"notifications": map[string]interface{}{
		"follow": map[string]interface{}{
			"title": "New follower",
			"body":  "{username} started following you.",
		},

		"join_request_sent": map[string]interface{}{
			"title": "New join request",
			"body":  "{username} requested to join \"{challenge}\".",
		},

		"join_request_accepted": map[string]interface{}{
			"title": "Request accepted",
			"body":  "Your request to join \"{challenge}\" was accepted.",
		},

		"invite_sent": map[string]interface{}{
			"title": "Challenge invite",
			"body":  "You were invited to join \"{challenge}\".",
		},

		"invite_accepted": map[string]interface{}{
			"title": "Invite accepted",
			"body":  "{username} accepted your invite to \"{challenge}\".",
		},

		"participant_joined": map[string]interface{}{
			"title": "New participant",
			"body":  "{username} joined your challenge \"{challenge}\".",
		},

		"challenge_reminder": map[string]interface{}{
			"title": "Challenge reminder",
			"body":  "It's time to log your progress for \"{challenge}\".",
		},

		"challenge_commented": map[string]interface{}{
			"title": "New comment",
			"body":  "{username} commented on \"{challenge}\": {comment}",
		},

		"challenge_liked": map[string]interface{}{
			"title": "New like",
			"body":  "{username} liked your challenge \"{challenge}\".",
		},
	},
}
