package localization

var Persian = map[string]interface{}{
	"title":            "عنوان",
	"description":      "توضیحات",
	"categoryID":       "دسته‌بندی",
	"category_id":      "دسته‌بندی",
	"maxParticipants":  "حداکثر شرکت‌کنندگان",
	"max_participants": "حداکثر شرکت‌کنندگان",
	"visibility":       "نوع نمایش",
	"location":         "موقعیت",
	"latitude":         "عرض جغرافیایی",
	"longitude":        "طول جغرافیایی",
	"address":          "آدرس",
	"goal":             "هدف",
	"rule":             "قانون",
	"startTime":        "زمان شروع",
	"start_time":       "زمان شروع",
	"endTime":          "زمان پایان",
	"end_time":         "زمان پایان",
	"timezone":         "منطقه زمانی",
	"file":             "فایل",

	"id":           "شناسه",
	"user_id":      "شناسه کاربر",
	"challenge_id": "شناسه چالش",
	"post_id":      "شناسه پست",
	"comment_id":   "شناسه نظر",
	"invite_id":    "شناسه دعوت",
	"request_id":   "شناسه درخواست",

	"date":      "تاریخ",
	"start":     "تاریخ شروع",
	"end":       "تاریخ پایان",
	"query":     "عبارت جستجو",
	"content":   "محتوا",
	"parent_id": "شناسه والد",

	"email":     "ایمیل",
	"newEmail":  "ایمیل جدید",
	"new_email": "ایمیل جدید",
	"oldEmail":  "ایمیل قبلی",
	"old_email": "ایمیل قبلی",
	"code":      "کد",

	"username": "نام کاربری",
	"bio":      "بیوگرافی",

	"progress": "پیشرفت",
	"feeling":  "احساس",
	"note":     "یادداشت",

	"count":        "تعداد",
	"contentType":  "نوع محتوا",
	"content_type": "نوع محتوا",

	"fields": map[string]interface{}{
		"title":            "عنوان",
		"description":      "توضیحات",
		"categoryID":       "دسته‌بندی",
		"category_id":      "دسته‌بندی",
		"maxParticipants":  "حداکثر شرکت‌کنندگان",
		"max_participants": "حداکثر شرکت‌کنندگان",
		"visibility":       "نوع نمایش",
		"location":         "موقعیت",
		"latitude":         "عرض جغرافیایی",
		"longitude":        "طول جغرافیایی",
		"address":          "آدرس",
		"goal":             "هدف",
		"rule":             "قانون",
		"startTime":        "زمان شروع",
		"start_time":       "زمان شروع",
		"endTime":          "زمان پایان",
		"end_time":         "زمان پایان",
		"timezone":         "منطقه زمانی",
		"file":             "فایل",

		"id":           "شناسه",
		"user_id":      "شناسه کاربر",
		"challenge_id": "شناسه چالش",
		"post_id":      "شناسه پست",
		"comment_id":   "شناسه نظر",
		"invite_id":    "شناسه دعوت",
		"request_id":   "شناسه درخواست",

		"date":      "تاریخ",
		"start":     "تاریخ شروع",
		"end":       "تاریخ پایان",
		"query":     "عبارت جستجو",
		"content":   "محتوا",
		"parent_id": "شناسه والد",

		"email":     "ایمیل",
		"newEmail":  "ایمیل جدید",
		"new_email": "ایمیل جدید",
		"oldEmail":  "ایمیل قبلی",
		"old_email": "ایمیل قبلی",
		"code":      "کد",

		"username": "نام کاربری",
		"bio":      "بیوگرافی",

		"progress": "پیشرفت",
		"feeling":  "احساس",
		"note":     "یادداشت",

		"count":        "تعداد",
		"contentType":  "نوع محتوا",
		"content_type": "نوع محتوا",
	},

	"errors": map[string]interface{}{
		// Generic
		"generic":  "خطایی رخ داده است، لطفاً دوباره تلاش کنید.",
		"internal": "خطای داخلی سرور.",

		// Auth / JWT
		"AUTH_MISSING_ID":          "ابتدا باید وارد شوید.",
		"AUTH_HEADER_MALFORMED":    "هدر احراز هویت نامعتبر است. فرمت صحیح: Bearer <توکن>",
		"TOKEN_EMPTY":              "توکن ارائه نشده است.",
		"TOKEN_INVALID_EXPIRED":    "توکن نامعتبر یا منقضی شده است.",
		"AUTH_INVALID_CREDENTIALS": "نام کاربری یا رمز عبور اشتباه است.",

		// Conflict (User, etc.)
		"USER_ALREADY_EXISTS":          "کاربری با این مشخصات قبلاً وجود دارد.",
		"USER_ALREADY_EXISTS_EMAIL":    "کاربری با این ایمیل از قبل وجود دارد.",
		"USER_ALREADY_EXISTS_USERNAME": "این نام کاربری قبلاً گرفته شده است.",
		"USER_UPDATE_CONFLICT":         "نام کاربری یا ایمیل قبلاً وجود دارد.",
		"USER_NOT_FOUND":               "کاربر یافت نشد.",
		"EMAIL_TAKEN":                  "این ایمیل قبلاً ثبت شده است.",

		// Validation
		"INPUT_VALIDATION_FAILED": "اعتبارسنجی ورودی ناموفق بود.",
		"INVALID_REQUEST_BODY":    "بدنه درخواست نامعتبر است.",
		"INVALID_URI_PARAMS":      "پارامترهای آدرس نامعتبر هستند.",
		"INVALID_PARAM":           "مقدار {0} نامعتبر است.",
		"INVALID_TIME_FORMAT":     "فرمت زمان {0} نامعتبر است.",
		"INVALID_DATE_FORMAT":     "فرمت تاریخ {0} نامعتبر است.",
		"USERNAME_REQUIRED":       "نام کاربری الزامی است.",
		"EMAIL_REQUIRED":          "ایمیل الزامی است.",
		"PASSWORD_REQUIRED":       "رمز عبور الزامی است.",
		"EMAIL_SAME":              "ایمیل جدید نمی‌تواند مشابه ایمیل فعلی باشد.",

		// Validator tags (from go-playground/validator)
		"required": "بخش {0} باید کامل شود.",
		"min":      "{0} باید حداقل {1} باشد.",
		"max":      "{0} باید حداکثر {1} باشد.",
		"len":      "طول {0} باید دقیقاً {1} باشد.",
		"email":    "فرمت ایمیل معتبر نیست.",
		"oneof":    "مقدار وارد شده برای {0} معتبر نیست.",
		"datetime": "فرمت تاریخ و زمان {0} معتبر نیست.",
		"numeric":  "{0} باید عددی باشد.",
		"alphanum": "{0} باید الفبایی-عددی باشد.",
		"ascii":    "{0} باید شامل کاراکترهای ASCII باشد.",
		"gte":      "{0} باید بزرگتر یا مساوی {1} باشد.",
		"lte":      "{0} باید کوچکتر یا مساوی {1} باشد.",
		"gt":       "{0} باید بزرگتر از {1} باشد.",
		"lt":       "{0} باید کوچکتر از {1} باشد.",
		"eqfield":  "{0} باید با {1} برابر باشد.",
		"nefield":  "{0} نباید با {1} برابر باشد.",
		"uuid":     "{0} باید یک UUID معتبر باشد.",
		"url":      "{0} باید یک آدرس اینترنتی معتبر باشد.",
		"base64":   "{0} باید یک رشته base64 معتبر باشد.",

		// Verification
		"VERIFY_CODE_INVALID":   "کد تأیید نامعتبر است.",
		"VERIFY_CODE_EXPIRED":   "کد تأیید منقضی شده است.",
		"EMAIL_CHANGE_EXPIRED":  "درخواست تغییر ایمیل منقضی شده است.",
		"EMAIL_CHANGE_MISMATCH": "درخواست تغییر ایمیل با کاربر مطابقت ندارد.",

		// Uploads & Media
		"INVALID_PROFILE_PICTURE": "تصویر پروفایل نامعتبر است.",
		"INVALID_CONTENT_TYPE":    "نوع محتوا پشتیبانی نمی‌شود.",
		"S3_UPLOAD_FAILED":        "آپلود تصویر ناموفق بود.",
		"COVER_FORBIDDEN":         "فقط ایجادکننده می‌تواند تصویر کاور را تغییر دهد.",
		"POST_TOO_MANY_IMAGES":    "حداکثر ۱۰ تصویر مجاز است.",
		"INVALID_TEMP_KEY":        "کلید موقت نامعتبر است.",
		"TEMP_VERIFY_FAILED":      "بررسی کلید موقت ناموفق بود.",
		"TEMP_KEY_NOT_OWNED":      "کلید موقت منقضی شده یا متعلق به شما نیست.",
		"COMMIT_FAILED":           "ثبت تصویر ناموفق بود.",
		"PRESIGN_FAILED":          "ایجاد لینک آپلود ناموفق بود.",

		// Posts
		"POST_CREATE_BAD_INPUT": "ورودی نامعتبر است.",
		"POST_NOT_FOUND":        "پست یافت نشد.",
		"POST_UPDATE_FORBIDDEN": "فقط ایجادکننده پست می‌تواند آن را ویرایش کند.",
		"POST_DELETE_FORBIDDEN": "فقط ایجادکننده پست می‌تواند آن را حذف کند.",
		"LIKE_BAD_INPUT":        "ورودی نامعتبر است.",
		"UNLIKE_BAD_INPUT":      "ورودی نامعتبر است.",
		"USER_NOT_LIKED":        "شما این مورد را لایک نکرده‌اید.",
		"USER_ALREADY_LIKED":    "قبلاً این مورد را لایک کرده‌اید.",
		"INVALID_ENTITY_TYPE":   "نوع موجودیت نامعتبر است.",
		"COMMENT_ADD_BAD_INPUT": "ورودی نامعتبر است.",
		"COMMENT_NOT_FOUND":     "نظر یافت نشد.",

		// Challenges
		"CHALLENGE_CREATE_BAD_INPUT":          "ورودی نامعتبر است.",
		"CHALLENGE_NOT_FOUND":                 "چالش یافت نشد.",
		"CHALLENGE_UPDATE_FORBIDDEN":          "فقط ایجادکننده می‌تواند چالش را ویرایش کند.",
		"CHALLENGE_DELETE_FORBIDDEN":          "فقط ایجادکننده می‌تواند چالش را حذف کند.",
		"STOP_CHALLENGE_NOT_AUTHORIZED":       "فقط ایجادکننده می‌تواند چالش را متوقف کند.",
		"INVALID_MAP_COORDINATES":             "مختصات نقشه نامعتبر است.",
		"MISSING_MAP_COORDINATES":             "عرض و طول جغرافیایی الزامی هستند.",
		"INVALID_GOAL":                        "هدف باید حداقل ۱ باشد.",
		"CHALLENGE_PARTICIPANT_LIMIT_REACHED": "ظرفیت شرکت‌کنندگان تکمیل شده است.",
		"CHALLENGE_NOT_PUBLIC":                "چالش عمومی نیست.",
		"CHALLENGE_NOT_PRIVATE":               "چالش خصوصی نیست.",
		"CHALLENGE_STOPPED":                   "چالش متوقف شده است.",
		"USER_ALREADY_PARTICIPANT":            "شما قبلاً عضو این چالش هستید.",
		"USER_NOT_PARTICIPANT":                "کاربر عضو این چالش نیست.",
		"PARTICIPANTS_ACCESS_DENIED":          "دسترسی به شرکت‌کنندگان مجاز نیست.",
		"INVITES_ACCESS_DENIED":               "فقط ایجادکننده می‌تواند دعوت‌ها را ببیند.",
		"REMOVE_PARTICIPANT_NOT_AUTHORIZED":   "فقط ایجادکننده می‌تواند شرکت‌کننده را حذف کند.",
		"JOIN_REQUEST_ALREADY_EXISTS":         "درخواست عضویت قبلاً ثبت شده است.",
		"JOIN_REQUEST_NOT_FOUND":              "درخواست عضویت یافت نشد.",
		"JOIN_REQUEST_NOT_PENDING":            "درخواست عضویت در انتظار نیست.",
		"JOIN_REQUEST_NOT_AUTHORIZED":         "شما مجاز به این عملیات نیستید.",
		"INVITE_NOT_FOUND":                    "دعوت یافت نشد.",
		"INVITE_NOT_PENDING":                  "دعوت در انتظار نیست.",
		"INVITE_NOT_AUTHORIZED":               "شما مجاز به این دعوت نیستید.",
		"COMMENTS_DISABLED":                   "نظرات برای این چالش غیرفعال است.",

		// IDs
		"INVALID_USER_ID":      "شناسه کاربر نامعتبر است.",
		"INVALID_POST_ID":      "شناسه پست نامعتبر است.",
		"INVALID_CHALLENGE_ID": "شناسه چالش نامعتبر است.",
		"INVALID_COMMENT_ID":   "شناسه نظر نامعتبر است.",
		"INVALID_INVITE_ID":    "شناسه دعوت نامعتبر است.",
		"INVALID_REQUEST_ID":   "شناسه درخواست نامعتبر است.",

		// UserDay
		"USER_ID_REQUIRED":      "شناسه کاربر الزامی است.",
		"CHALLENGE_ID_REQUIRED": "شناسه چالش الزامی است.",
		"NOTE_EMPTY":            "یادداشت نمی‌تواند خالی باشد.",
		"INVALID_FEELING":       "احساس باید «خوب» یا «بد» باشد.",
		"INVALID_DATE_RANGE":    "تاریخ شروع باید قبل از تاریخ پایان باشد.",
		"INVALID_GOAL_VALUE":    "مقدار پیشرفت باید بین ۰ تا ۱۰۰ باشد.",

		// Follow
		"SELF_FOLLOW_FORBIDDEN": "نمی‌توانید خودتان را فالو کنید.",
		"FOLLOW_ALREADY_EXISTS": "شما قبلاً این کاربر را فالو کرده‌اید.",
		"FOLLOW_NOT_FOUND":      "رابطه فالو یافت نشد.",
		"FOLLOWER_NOT_FOUND":    "فالوور مورد نظر یافت نشد.",

		// System / Internal
		"DB_OPERATION_FAILED":      "خطا در انجام عملیات پایگاه داده.",
		"SYSTEM_HASH_FAIL":         "خطای داخلی سرور.",
		"SYSTEM_JWT_FAIL":          "خطای داخلی سرور.",
		"SYSTEM_VERIFY_FAIL":       "خطای داخلی سرور.",
		"SYSTEM_EMAIL_FAIL":        "خطای داخلی سرور.",
		"DB_LOGIN_FAIL":            "خطای داخلی سرور.",
		"DB_VERIFY_FAIL":           "خطای داخلی سرور.",
		"DB_UPDATE_FAIL":           "خطای داخلی سرور.",
		"VERIFY_CODE_GEN_FAIL":     "خطای داخلی سرور.",
		"CONTEXT_CAST_FAIL":        "خطای داخلی سرور.",
		"CODE_LOGIC_ERROR":         "خطای داخلی سرور.",
		"CODE_DATA_CORRUPT":        "خطای داخلی سرور.",
		"STORAGE_OPERATION_FAILED": "خطا در انجام عملیات ذخیره‌سازی.",
	},

	"success": map[string]interface{}{
		"PROFILE_UPDATED":                "پروفایل با موفقیت بروزرسانی شد.",
		"PROFILE_EMAIL_UPDATED_RELOGIN":  "پروفایل و ایمیل بروزرسانی شد. لطفاً دوباره وارد شوید.",
		"EMAIL_CHANGE_VERIFICATION_SENT": "ایمیل تأیید به ایمیل جدید ارسال شد.",
		"EMAIL_CHANGED_SUCCESSFULLY":     "ایمیل با موفقیت تغییر کرد.",
		"USER_DELETED_SUCCESSFULLY":      "کاربر با موفقیت حذف شد.",
		"PROFILE_PICTURE_UPLOADED":       "تصویر پروفایل با موفقیت آپلود شد.",
		"CHALLENGE_CREATED":              "چالش با موفقیت ایجاد شد.",
		"CHALLENGE_UPDATED":              "چالش با موفقیت بروزرسانی شد.",
		"CHALLENGE_DELETED":              "چالش با موفقیت حذف شد.",
		"DAY_DATA_SAVED":                 "اطلاعات روز ذخیره شد.",
		"DAY_DATA_UPDATED":               "اطلاعات روز بروزرسانی شد.",
		"DAY_DATA_DELETED":               "اطلاعات روز حذف شد.",
		"FOLLOW_SUCCESS":                 "کاربر با موفقیت فالو شد.",
		"UNFOLLOW_SUCCESS":               "فالو با موفقیت لغو شد.",
		"CHALLENGE_JOINED":               "به چالش با موفقیت پیوستید.",
		"CHALLENGE_LEFT":                 "از چالش خارج شدید.",
		"INVITE_SENT":                    "دعوت‌نامه با موفقیت ارسال شد.",
		"INVITE_ACCEPTED":                "دعوت‌نامه پذیرفته شد.",
		"INVITE_DECLINED":                "دعوت‌نامه رد شد.",
		"REQUEST_SENT":                   "درخواست عضویت ارسال شد.",
		"REQUEST_ACCEPTED":               "درخواست عضویت پذیرفته شد.",
		"REQUEST_DECLINED":               "درخواست عضویت رد شد.",
		"COMMENT_ADDED":                  "نظر با موفقیت ارسال شد.",
		"LIKE_ADDED":                     "پست لایک شد.",
		"LIKE_REMOVED":                   "لایک پست لغو شد.",
		"USER_REGISTERED":                "کاربر با موفقیت ثبت‌نام شد. لطفاً ایمیل خود را برای تأیید چک کنید.",
	},

	"notifications": map[string]interface{}{
		"follow": map[string]interface{}{
			"title": "دنبال‌کننده جدید",
			"body":  "{username} شما را دنبال کرد.",
		},

		"join_request_sent": map[string]interface{}{
			"title": "درخواست عضویت جدید",
			"body":  "{username} درخواست عضویت در چالش «{challenge}» را ارسال کرد.",
		},

		"join_request_accepted": map[string]interface{}{
			"title": "درخواست پذیرفته شد",
			"body":  "درخواست عضویت شما در چالش «{challenge}» پذیرفته شد.",
		},

		"invite_sent": map[string]interface{}{
			"title": "دعوت به چالش",
			"body":  "شما به چالش «{challenge}» دعوت شده‌اید.",
		},

		"invite_accepted": map[string]interface{}{
			"title": "دعوت پذیرفته شد",
			"body":  "{username} دعوت شما به چالش «{challenge}» را پذیرفت.",
		},

		"participant_joined": map[string]interface{}{
			"title": "عضو جدید چالش",
			"body":  "{username} به چالش «{challenge}» پیوست.",
		},

		"challenge_reminder": map[string]interface{}{
			"title": "یادآوری چالش",
			"body":  "زمان ثبت پیشرفت برای چالش «{challenge}» فرا رسیده است.",
		},

		"challenge_commented": map[string]interface{}{
			"title": "نظر جدید",
			"body":  "{username} در چالش «{challenge}» نظر داد: {comment}",
		},

		"challenge_liked": map[string]interface{}{
			"title": "لایک جدید",
			"body":  "{username} چالش «{challenge}» را لایک کرد.",
		},
	},
}
